version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    command: 'mongod --port 27017'
    volumes:
      - mongodb:/data/db
  backend:
    image: registry.cn-hangzhou.aliyuncs.com/colinaaa/ddwp-backend:dev
    env_file:
      - .env
      - ./env/development.env
    environment:
      - NODE_ENV=development
    ports:
      - 4000:4000
    links:
      - mongodb
      - redis
    volumes:
      - ./logs:/usr/src/backend/logs

volumes:
  mongodb:
