version: '3'
services:
  redis:
    image: redis:alpine
  mongodb:
    image: mongo:latest
    command: 'mongod --port ${DB_PORT}'
    volumes:
      - mongodb:/data/db
  backend:
    build: .
    env_file:
      - .env
      - ./env/production.env
    environment:
      - NODE_ENV=production
    ports:
      - 4000:4000
    links:
      - mongodb
      - redis
    volumes:
      - ./logs:/usr/src/backend/logs

volumes:
  mongodb:
